---
dist: trusty
language: go
go:
  - "1.21.9"

group: bluezone

matrix:
  fast_finish: true
  allow_failures:
  - go: tip
  include:
    - os: linux
      env: MAKE_TASK="fmt"
    - os: linux
      env: MAKE_TASK="test-sanity"
    - os: linux
      env: MAKE_TASK="test"

cache:
  bundler: true

sudo: true
services:
  - docker

before_script:
  - rm -rf ~/.cache/go-build
  - sudo apt-get install glibc-static
  - make $MAKE_TASK

script:
  if [[ "$MAKE_TASK" == "fmt" ]]; then
    make driver;
  fi
