apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
# TODO example annotations
#commonAnnotations:
#  cosi.storage.k8s.io/authors: "Kubernetes Authors"
#  cosi.storage.k8s.io/license: "Apache V2"
#  cosi.storage.k8s.io/support: "https://github.com/kubernetes-sigs/container-object-storage-api"
#commonLabels:
#  cosi.storage.k8s.io/version: "dev"

resources:
  - deploy/cos-csi-s3-attacher.yaml
  - deploy/cos-csi-s3-driver.yaml
  - deploy/cos-csi-s3-provisioner-v3.yaml
  - deploy/cos-csi-s3-sc-v3.yaml
