apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: debugger-daemonset
spec:
  selector:
    matchLabels:
      app: debugger
  template:
    metadata:
      labels:
        app: debugger
    spec:
      containers:
      - name: debugger
        image: ambikanair/grpctest:v1
        imagePullPolicy: Always
        tty: true
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /host
          name: host-root
        command: ["/bin/sh", "-c", "./mh-install.sh"]
      hostIPC: true
      hostNetwork: true
      hostPID: true
      preemptionPolicy: PreemptLowerPriority
      priority: 0
      restartPolicy: Always
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      tolerations:
      - operator: Exists
      volumes:
      - hostPath:
          path: /
          type: ""
        name: host-root
