---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cos-s3-csi-sc
  labels:
    app.kubernetes.io/part-of=ibm-object-csi-driver
provisioner: cos.s3.csi.ibm.io
parameters:
  mounter: "s3fs"
  client: "awss3"
  csi.storage.k8s.io/provisioner-secret-name: ${pvc.name}
  csi.storage.k8s.io/provisioner-secret-namespace: ${pvc.namespace}
  csi.storage.k8s.io/node-publish-secret-name: ${pvc.name}
  csi.storage.k8s.io/node-publish-secret-namespace: ${pvc.namespace}
