---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cos-csi-s3-sc-v3
provisioner: cos-csi-s3-driver
parameters:
  mounter: "s3fs"
  client: "awss3"
  csi.storage.k8s.io/provisioner-secret-name: ${pvc.name}
  csi.storage.k8s.io/provisioner-secret-namespace: ${pvc.namespace}
  csi.storage.k8s.io/node-publish-secret-name: ${pvc.name}
  csi.storage.k8s.io/node-publish-secret-namespace: ${pvc.namespace}
