---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-attacher
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-attacher-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-attacher-rolebind
subjects:
  - kind: ServiceAccount
    name: csi-attacher
    namespace: default
roleRef:
  kind: ClusterRole
  name: csi-attacher-role
  apiGroup: rbac.authorization.k8s.io
---
kind: Service
apiVersion: v1
metadata:
  name: cos-csi-s3-attacher
  labels:
    app: cos-csi-s3-attacher
spec:
  selector:
    app: cos-csi-s3-attacher
  ports:
    - name: dummy
      port: 12345

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: cos-csi-s3-attacher
spec:
  serviceName: "cos-csi-s3-attacher"
  replicas: 1
  selector:
    matchLabels:
      app: cos-csi-s3-attacher
  template:
    metadata:
      labels:
        app: cos-csi-s3-attacher
    spec:
      serviceAccountName: csi-attacher
      containers:
        - name: csi-attacher
          # https://github.com/kubernetes-csi/external-attacher/releases/tag/v1.0.1
          # docker pull quay.io/k8scsi/csi-attacher:v1.0.1
          image: gcr.io/gke-release/csi-attacher:v1.0.1-gke.0
          args:
            - --v=5
            - --csi-address=$(ADDRESS)
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /csi
            name: socket-dir
      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/csi-s3-driver
            type: DirectoryOrCreate
          name: socket-dir
