---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cos-csi-s3-sc
provisioner: cos-csi-s3-driver
parameters:
  mounter: "s3fs"
  client: "awss3"
  csi.storage.k8s.io/provisioner-secret-name: nk-cos-secret
  csi.storage.k8s.io/provisioner-secret-namespace: default
  csi.storage.k8s.io/node-publish-secret-name: nk-cos-secret
  csi.storage.k8s.io/node-publish-secret-namespace: default
