apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-cos-s3-pvc-v3
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  storageClassName: cos-csi-s3-sc-v3
