apiVersion: v1
kind: Secret
type: cos-csi-s3-driver
metadata:
  name: nk-cos-secret 
data:
  # echo -n "https://s3.ap-geo.objectstorage.softlayer.net" | base64
  cos-endpoint: aHR0cHM6Ly9zMy5hcC1nZW8ub2JqZWN0c3RvcmFnZS5zb2Z0bGF5ZXIubmV0
  # echo -n "ap-standard" | base64
  regn-class: YXAtc3RhbmRhcmQ= 
  # echo -n "nkapdevtest" | base64
  bucket-name: bmthcGRldnRlc3Q=
  access-key: <echo -n "access key id" | base64>
  secret-key: <echo -n "secret access key " | base64>

